version: '3.8'

services:
  db:
    image: postgres:14.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB-constricon}
      POSTGRES_USER: ${POSTGRES_USER-constricon_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-OwOtBep9Frut}

  backend:
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - 8080:8080
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/code/frontend
    ports:
      - 80:80

volumes:
  db_data:
